# Generated by Django 2.2 on 2019-08-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='book.Shelf'),
        ),
    ]
